### ISSUE TITLE
Unicode Characters Don't Work in Profile Taglines

### ISSUE THREAD

**Issue by zmattingly** [jp00p/AGIMUS#350]
This should be "DÄRMOK and JÅLAD" for example:

![image](https://user-images.githubusercontent.com/1075211/191888971-328f47ea-ccaa-4249-aa9c-b6832de08873.png)

**Comment by thousand** [comment]
Looks like the `/profile set_tagline` command forces ascii and strips them: https://github.com/jp00p/AGIMUS/blob/main/cogs/profile.py#L322 . The DB looks to be set up with `utf8mb4` and the fonts for this have support most of the latin character set as well. Any reason this needs to be so limited? Otherwise the [`strip_emoji` util here](https://github.com/jp00p/AGIMUS/blob/main/utils/string_utils.py#L38) would probably be sufficient input sanitation.

**Comment by thousand** [comment]
Fix should to out with the bigger profile revamp in #352
